### ISSUE TITLE
HTTP/1.1 500: TypeError: item._embedded.wp:term.flatMap is not a function

### ISSUE THREAD

**Issue by rye** [frog-pond/ccc-server#165]
From production:
```console
  xxx GET /v1/news/named/stolaf 500 520ms -

  TypeError: item._embedded.wp:term.flatMap is not a function
      at convertWpJsonItemToStory (/app/modules/node_modules/@frogpond/ccc-wpjson-feed/index.js:13:42)
      at Array.map (<anonymous>)
      at fetchWpJson (/app/modules/node_modules/@frogpond/ccc-wpjson-feed/index.js:7:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Possible regression introduced by 20ef0a13a9ea9b181a10cfc5ca4085eee5458bd8?

**Comment by hawkrives** [comment]
Closed by #166
